/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx}",
  ],
  theme: {
    extend: {
      colors: {
        'tertiary-container': '#571f00',
        'on-tertiary': '#ffffff',
        'error-container': '#ffdad6',
        'surface-dim': '#d8dade',
        'on-tertiary-container': '#d7835b',
        'on-primary': '#ffffff',
        'on-primary-fixed': '#001947',
        'tertiary-fixed': '#ffdbcc',
        'on-primary-fixed-variant': '#284483',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'inverse-surface': '#2e3134',
        'tertiary': '#351000',
        'error': '#ba1a1a',
        'surface': '#f8f9fd',
        'on-background': '#191c1f',
        'inverse-on-surface': '#eff1f5',
        'surface-bright': '#f8f9fd',
        'secondary': '#555e79',
        'on-secondary-container': '#59627d',
        'on-secondary-fixed-variant': '#3d4660',
        'on-secondary': '#ffffff',
        'on-tertiary-fixed-variant': '#743412',
        'tertiary-fixed-dim': '#ffb694',
        'surface-variant': '#e1e2e7',
        'surface-container-low': '#f2f3f8',
        'on-surface-variant': '#444650',
        'surface-tint': '#425c9c',
        'on-secondary-fixed': '#111b32',
        'primary-fixed': '#dae2ff',
        'surface-container-lowest': '#ffffff',
        'background': '#f8f9fd',
        'primary': '#001947',
        'surface-container': '#eceef2',
        'inverse-primary': '#b1c5ff',
        'secondary-fixed': '#dae2ff',
        'primary-fixed-dim': '#b1c5ff',
        'on-primary-container': '#7d97db',
        'secondary-fixed-dim': '#bdc6e5',
        'surface-container-highest': '#e1e2e7',
        'on-tertiary-fixed': '#351000',
        'primary-container': '#0b2d6b',
        'outline': '#747781',
        'outline-variant': '#c4c6d2',
        'secondary-container': '#d6dfff',
        'on-surface': '#191c1f',
        'surface-container-high': '#e7e8ec',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'margin-desktop': '48px',
        'base-unit': '8px',
        'gutter': '24px',
        'container-max-width': '1200px',
        'margin-mobile': '16px',
      },
      fontFamily: {
        'technical-label': ['JetBrains Mono', 'monospace'],
        'code-sm': ['JetBrains Mono', 'monospace'],
        'display-lg-mobile': ['Space Grotesk', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'display-lg': ['Space Grotesk', 'sans-serif'],
        'headline-md': ['Space Grotesk', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'technical-label': ['14px', { lineHeight: '1.4', letterSpacing: '0.05em', fontWeight: '500' }],
        'code-sm': ['13px', { lineHeight: '1.4', fontWeight: '400' }],
        'display-lg-mobile': ['32px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}
